### PR TITLE
docs: add shields to readme

### PR DESCRIPTION
**Pull request by nyurik**
Just some useful quick links to help users

### CODE REVIEW

**Comment by SeedyROM** [comment]
Damn you beat me to it!

**Comment by nyurik** [comment]
hehe, i just noticed the license files are actually missing - so the license link doesn't work properly (I copied it from one of my other projects). Want to re-license it as `MIT OR APACHE` like most other rust code?

**Comment by SeedyROM** [comment]
Yes, MIT is my choice for most things. Let me do that quick.

**Comment by SeedyROM** [comment]
@nyurik Done! Gonna stop saying thank you, but thank you hahaha.

**Comment by nyurik** [comment]
I like MIT too, but it has a big drawback for some users -- in theory you can publish MIT code, but later claim you own patents for the code you published, and start suing people (although I don't know if this has ever been tested in courts). So when someone publishes under dual-license of MIT and Apache, it gives users a bit more flexibility and certainty in the future of the code. This is just my understanding of it.   Anyway, time to go to bed, its pretty late in NY :)

**Pull request merged**
